apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
    - name: build-and-push
      taskRef:
        name: build-and-push
